### ISSUE TITLE
Harfbuzz dependency in dub project can not use ft support

### ISSUE THREAD

**Issue by tofuninja** [DlangGraphicsWG/bindbc-harfbuzz#4]
If you use this as dependency in dub project dub will not pass the bind-bc-freetype dependency to this package even if the parent project uses it.  Requires modification of the dub project file to make it work... there should be configurations to add these dependencies..

**Comment by ahmetsait** [comment]
Can you expand on this a bit more? It supposed to just work™️ if you put bindbc-freetype dependency alongside bindbc-harfbuzz.

**Comment by ahmetsait** [comment]
Actually no, you need to specificy both `"versions": ["HB_with_freetype"]` and `"dependencies": {"bindbc-freetype": "~>0.8.0"}` in your dub.json file to make it work - but this should be clear in the readme. If you're using a package that already does use bindbc-freetype then it should work without you having to put it as a dependency yourself but I didn't test that case. (it should work as long as dub passes `Have_bindbc_freetype` version when buiding)

**Comment by tofuninja** [comment]
[repro.zip](https://github.com/DlangGraphicsWG/bindbc-harfbuzz/files/4468333/repro.zip)

**Comment by tofuninja** [comment]
Please fix this issue
